import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/header/page";
import Footer from "./_component/footer/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
